server:
  port: 80

spring:
  application:
    name: gps
  servlet:
    multipart:
      #最大上传
      max-file-size: 1000MB
#minio
minio:
  url: http://127.0.0.1:9000
  accessKey: YUY5yX5zPpfeWYEiWeGa
  secretKey: JdN35b6OKwPvwtlfKkcd58UGy0h6d8cghUPJtagf
  bucketName: gps01
  partSize: 104857600

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

